export const STREETCLIP_CANDIDATE_LABELS = [
  "United States",
  "Canada",
  "Mexico",
  "Guatemala",
  "Costa Rica",
  "Panama",
  "Colombia",
  "Ecuador",
  "Peru",
  "Bolivia",
  "Chile",
  "Argentina",
  "Uruguay",
  "Paraguay",
  "Brazil",
  "United Kingdom",
  "Ireland",
  "France",
  "Spain",
  "Portugal",
  "Belgium",
  "Netherlands",
  "Luxembourg",
  "Germany",
  "Switzerland",
  "Austria",
  "Italy",
  "Denmark",
  "Norway",
  "Sweden",
  "Finland",
  "Iceland",
  "Poland",
  "Czechia",
  "Slovakia",
  "Hungary",
  "Slovenia",
  "Croatia",
  "Serbia",
  "Bosnia and Herzegovina",
  "Montenegro",
  "North Macedonia",
  "Albania",
  "Greece",
  "Romania",
  "Bulgaria",
  "Moldova",
  "Ukraine",
  "Belarus",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Russia",
  "Turkey",
  "Georgia",
  "Armenia",
  "Kazakhstan",
  "Morocco",
  "Tunisia",
  "Egypt",
  "South Africa",
  "Namibia",
  "Botswana",
  "Zimbabwe",
  "Zambia",
  "Kenya",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "Ghana",
  "Japan",
  "South Korea",
  "Taiwan",
  "Thailand",
  "Vietnam",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Singapore",
  "Sri Lanka",
  "Nepal",
  "India",
  "Israel",
  "Jordan",
  "Saudi Arabia",
  "United Arab Emirates",
  "Australia",
  "New Zealand"
] as const;
